### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by valentin-aleksandrov** [TheaAleksovDev/angularNotesProject#4]
![image](https://github.com/user-attachments/assets/104f43df-a24d-4d52-b192-47995747ee89)
Add min-width to these items.

**Comment by TheaAleksovDev** [comment]
Will it be necessary to make everything responsive in these projects? Can we fully focus on concepts and have designs just for basic functionality?

**Comment by valentin-aleksandrov** [comment]
I think you're right. Fully focusing on the concepts it's the best way to go about it.

**Comment by TheaAleksovDev** [comment]
Great! I'm glad that you agreed.
